<?php
// test_export_demo.php - Simple test for export functionality
require_once 'SimpleXLSXWriter.php';

// Test the Excel writer with sample data
$excel = new SimpleXLSXWriter('Test_Export_Demo');

// Set headers
$headers = [
    'Student ID',
    'Student Name', 
    'Course',
    'Violation Type',
    'Date',
    'Status'
];
$excel->setHeaders($headers);

// Add sample data
$sampleData = [
    ['220342', 'Joshua P. Basco', 'BSCS', 'No ID', '2025-09-09', 'Active'],
    ['220000', 'Jasper Andam', 'BSIT', 'Late Arrival', '2025-09-08', 'Resolved'],
    ['220353', 'Nashria Macalatas', 'BSCS', 'Uniform Violation', '2025-09-07', 'Pending'],
    ['220123', 'Mike Kevin Obumani', 'BSIT', 'No ID', '2025-09-06', 'Active'],
    ['220043', 'Oliver Burro', 'BSCS', 'Tardiness', '2025-09-05', 'Resolved']
];

foreach ($sampleData as $row) {
    $excel->addRow($row);
}

// Add a separator and summary section
$excel->addRow(['']); // Empty row
$excel->addRow(['=== SUMMARY ===']);
$excel->addRow(['Total Records', count($sampleData)]);
$excel->addRow(['Export Date', date('Y-m-d H:i:s')]);
$excel->addRow(['Generated By', 'RFID Attendance System']);

// Download the file
$excel->downloadAsExcelHTML();
?>